from faker import Faker
f= Faker('tr')
f.name()
f.address()
f.email()
f.phone_number()
print(f'name: {f.name()}')
print(f'address: {f.address()}')
print(f'mail: {f.email()}')
print(f'phone: {f.phone_number()}')
